### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CleitonDeLima** [CleitonDeLima/django-easy-formset#4]
- [ ] Add `can_order`
- [x] Add event triggers
- [x] Hide `deleteHTML` when you can't delete
- [x] Hide add button
- [x] Fixbug: hide nodes correctly
- [x] Rename revert to undo

**Comment by imshubhdj** [comment]
revert option does not show up after delete? Am I missing something?

**Comment by CleitonDeLima** [comment]
> revert option does not show up after delete? Am I missing something?

The reversion option only appears when there is an id to the form, for example, inlineformsets or modelformsets (in editing). If you still have problems show your code so I can see the problem.

**Comment by imshubhdj** [comment]
Okay got it!! I was trying formset_factory so was not able to see it.... 
Thanks

**Comment by CleitonDeLima** [comment]
It would be interesting to revert to any case, it's an idea ...

**Comment by shawnngtq** [comment]
Personally, I find implementing `inlineformset_factory` to be a real pain, so very interested if this library can make it simple. It will be perfect if this is integrated with django crispy form
